import {
  getDockerComposes,
  createDockerCompose,
  updateDockerCompose,
  deleteDockerCompose,
  renameDockerCompose,
  addServiceToCompose,
  updateServiceInCompose,
  removeServiceFromCompose,
  upCompose,
  deployCompose,
  stopCompose,
  downCompose,
  startService,
  stopService,
  terminateService,
  rebootService,
  deployService,
} from '@/app/(docker)/docker/server/compose-actions';
import { getCurrentDockerContext, getDockerContexts } from '@/app/(docker)/docker/server/context-actions';

export const docker = {
  getCurrentDockerContext,
  getDockerContexts,
  getDockerComposes,
  createDockerCompose,
  updateDockerCompose,
  deleteDockerCompose,
  renameDockerCompose,
  addServiceToCompose,
  updateServiceInCompose,
  removeServiceFromCompose,
  upCompose,
  deployCompose,
  stopCompose,
  downCompose,
  startService,
  stopService,
  terminateService,
  rebootService,
  deployService,
};
