import {
  addServiceToCompose,
  createDockerCompose,
  deleteDockerCompose,
  deployCompose,
  deployService,
  downCompose,
  getDockerComposes,
  rebootService,
  removeServiceFromCompose,
  renameDockerCompose,
  startService,
  stopCompose,
  stopService,
  terminateService,
  upCompose,
  updateDockerCompose,
  updateServiceInCompose,
} from '@/app/(docker)/_server/compose-actions'
import { getCurrentDockerContext, getDockerContexts } from '@/app/(docker)/_server/context-actions'

export const docker = {
  getCurrentDockerContext,
  getDockerContexts,
  getDockerComposes,
  createDockerCompose,
  updateDockerCompose,
  deleteDockerCompose,
  renameDockerCompose,
  addServiceToCompose,
  updateServiceInCompose,
  removeServiceFromCompose,
  upCompose,
  deployCompose,
  stopCompose,
  downCompose,
  startService,
  stopService,
  terminateService,
  rebootService,
  deployService,
}
